-- Adds a photo_path column to students and a private storage bucket for student photos.
alter table public.students add column if not exists photo_path text;

-- Storage bucket for student photos. Kept private; access is via RLS-scoped
-- signed URLs generated by the app, not public links.
insert into storage.buckets (id, name, public)
values ('student-photos', 'student-photos', false)
on conflict (id) do nothing;

drop policy if exists "student_photos_owner_access" on storage.objects;
create policy "student_photos_owner_access" on storage.objects for all
  using (
    bucket_id = 'student-photos'
    and (
      (storage.foldername(name))[1] = auth.uid()::text
      or exists (select 1 from public.user_profiles up where up.user_id = auth.uid() and up.role = 'admin')
    )
  )
  with check (
    bucket_id = 'student-photos'
    and (storage.foldername(name))[1] = auth.uid()::text
  );
