-- Classwork table: one entry per class/date/subject, with an optional photo stored in Supabase Storage.
create table if not exists public.classwork (
  id uuid primary key default extensions.gen_random_uuid(),
  teacher_user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  "className" text not null,
  subject text,
  notes text,
  photo_path text,
  classwork_date date not null,
  created_at timestamptz not null default now()
);

alter table public.classwork enable row level security;

drop policy if exists "classwork_owner_access" on public.classwork;
create policy "classwork_owner_access" on public.classwork for all
  using (
    teacher_user_id = auth.uid()
    or exists (select 1 from public.user_profiles up where up.user_id = auth.uid() and up.role = 'admin')
  )
  with check (
    teacher_user_id = auth.uid()
    or exists (select 1 from public.user_profiles up where up.user_id = auth.uid() and up.role = 'admin')
  );

grant select, insert, update, delete on public.classwork to authenticated;

-- Storage bucket for classwork photos. Kept private; access is via RLS-scoped
-- signed URLs generated by the app, not public links.
insert into storage.buckets (id, name, public)
values ('classwork-photos', 'classwork-photos', false)
on conflict (id) do nothing;

drop policy if exists "classwork_photos_owner_access" on storage.objects;
create policy "classwork_photos_owner_access" on storage.objects for all
  using (
    bucket_id = 'classwork-photos'
    and (
      (storage.foldername(name))[1] = auth.uid()::text
      or exists (select 1 from public.user_profiles up where up.user_id = auth.uid() and up.role = 'admin')
    )
  )
  with check (
    bucket_id = 'classwork-photos'
    and (storage.foldername(name))[1] = auth.uid()::text
  );
